### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by winderzhang** [yeungchenwa/OCR-SAM#35]
Inference ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   
Traceback (most recent call last):
  File "mmocr_sam_erase.py", line 215, in <module>
    result = mmocr_inferencer(
  File "/data/home/winderzhang/.conda/envs/ocr-sam/lib/python3.8/site-packages/mmocr/apis/inferencers/mmocr_inferencer.py", line 317, in __call__
    preds = self.forward(
  File "/data/home/winderzhang/.conda/envs/ocr-sam/lib/python3.8/site-packages/mmocr/apis/inferencers/mmocr_inferencer.py", line 154, in forward
    result['det'] = self.textdet_inferencer(
  File "/data/home/winderzhang/.conda/envs/ocr-sam/lib/python3.8/site-packages/mmocr/apis/inferencers/base_mmocr_inferencer.py", line 193, in __call__
    preds = self.forward(data, **forward_kwargs)
  File "/data/home/winderzhang/.conda/envs/ocr-sam/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/data/home/winderzhang/.conda/envs/ocr-sam/lib/python3.8/site-packages/mmengine/infer/infer.py", line 296, in forward
    return self.model.test_step(inputs)
  File "/data/home/winderzhang/.conda/envs/ocr-sam/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 145, in test_step
    return self._run_forward(data, mode='predict')  # type: ignore
  File "/data/home/winderzhang/.conda/envs/ocr-sam/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 340, in _run_forward
    results = self(**data, mode=mode)
  File "/data/home/winderzhang/.conda/envs/ocr-sam/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/home/winderzhang/.conda/envs/ocr-sam/lib/python3.8/site-packages/mmocr/models/textdet/detectors/base.py", line 74, in forward
    return self.predict(inputs, data_samples)
  File "/data/home/winderzhang/.conda/envs/ocr-sam/lib/python3.8/site-packages/mmocr/models/textdet/detectors/single_stage_text_detector.py", line 106, in predict
    x = self.extract_feat(inputs)
  File "/data/home/winderzhang/.conda/envs/ocr-sam/lib/python3.8/site-packages/mmocr/models/textdet/detectors/single_stage_text_detector.py", line 57, in extract_feat
    inputs = self.backbone(inputs)
  File "/data/home/winderzhang/.conda/envs/ocr-sam/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/home/winderzhang/.conda/envs/ocr-sam/lib/python3.8/site-packages/mmcls/models/backbones/swin_transformer_v2.py", line 478, in forward
    x, hw_shape = self.patch_embed(x)
  File "/data/home/winderzhang/.conda/envs/ocr-sam/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/home/winderzhang/.conda/envs/ocr-sam/lib/python3.8/site-packages/mmcv/cnn/bricks/transformer.py", line 270, in forward
    x = self.projection(x)
  File "/data/home/winderzhang/.conda/envs/ocr-sam/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/home/winderzhang/.conda/envs/ocr-sam/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/data/home/winderzhang/.conda/envs/ocr-sam/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 453, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR

**Comment by Mountchicken** [comment]
Hi @winderzhang 
You can check this blog to see if it helps https://saturncloud.io/blog/pytorch-model-training-runtimeerror-cudnn-error-cudnnstatusinternalerror/

**Comment by winderzhang** [comment]
this is env problem
